# Generated by Django 5.1.7 on 2025-06-15 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True)),
                ('registration_no', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Tipper', 'Tipper'), ('Excavator', 'Excavator'), ('Paver', 'Paver'), ('Dozer', 'Dozer'), ('B-Tempo', 'B-Tempo'), ('Bus', 'Bus'), ('Camper', 'Camper'), ('Farana', 'Farana'), ('Grader', 'Grader'), ('Loader', 'Loader'), ('Backhoe Loader', 'Backhoe Loader'), ('Roller', 'Roller'), ('Service Van', 'Service Van'), ('Trailor', 'Trailor'), ('Transit Mixer', 'Transit Mixer'), ('Water Tanker', 'Water Tanker'), ('Wagon Drill', 'Wagon Drill'), ('Bitumen Bowser', 'Bitumen Bowser'), ('Diesel Tanker', 'Diesel Tanker'), ('Personal Vehicle', 'Personal Vehicle'), ('Two Wheeler', 'Two Wheeler'), ('Pick Up', 'Pick Up'), ('Crane', 'Crane')], max_length=50)),
                ('owner', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('vehicle', 'vehicle'), ('machinery', 'machinery')], max_length=50)),
                ('purchase_value', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('chasis_no', models.CharField(max_length=30)),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi_provider', models.CharField(max_length=100)),
                ('emi_payment_date', models.DateField()),
                ('emi_start_date', models.DateField()),
                ('emi_end_date', models.DateField()),
                ('insurance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_provider', models.CharField(max_length=100)),
                ('insurance_validity', models.DateField(null=True)),
                ('puc_start_date', models.DateField()),
                ('puc_end_date', models.DateField()),
                ('ot_road_tax', models.BooleanField()),
                ('fitness_start_date', models.DateField(null=True)),
                ('fitness_end_date', models.DateField(null=True)),
                ('road_tax_start_date', models.DateField(null=True)),
                ('road_tax_end_date', models.DateField(null=True)),
                ('permit_start_date', models.DateField()),
                ('permit_end_date', models.DateField()),
                ('rate_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_hr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_shift', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chargers', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DieselStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.IntegerField(unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('party_name', models.CharField(max_length=255)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244)),
                ('role', models.CharField(max_length=244)),
                ('type', models.CharField(max_length=244)),
                ('salary', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('sub_grade', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('salary', models.IntegerField(null=True)),
                ('grade', models.CharField(max_length=10)),
                ('sub_grade', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DieselEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('site', models.CharField(max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnm.asset')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pnm.manager')),
            ],
        ),
        migrations.CreateModel(
            name='AssetManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255)),
                ('date_assigned', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='pnm.asset')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnm.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('salary', models.IntegerField(null=True)),
                ('grade', models.CharField(max_length=10)),
                ('sub_grade', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('site', models.CharField(max_length=255)),
                ('issue', models.TextField()),
                ('action_taken', models.TextField(null=True)),
                ('estimated_delivery_date', models.DateField(null=True)),
                ('delivered_at_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=50)),
                ('cost', models.IntegerField(null=True)),
                ('manpower_cost', models.IntegerField(null=True)),
                ('material_used', models.CharField(max_length=255, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_occurred', to='pnm.asset')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pnm.manager')),
                ('mechanic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pnm.mechanic')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('rate_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_hr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_shift', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnm.asset')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pnm.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('trip', 'Trip Update'), ('diesel', 'Diesel Entry'), ('breakdown', 'Breakdown'), ('general', 'General')], default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255, null=True)),
                ('material', models.CharField(max_length=255, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('deal_type', models.CharField(choices=[('Sale', 'Sale'), ('Purchase', 'Purchase'), ('Shifting', 'Shifting')], max_length=50)),
                ('hours', models.IntegerField(null=True)),
                ('shift', models.IntegerField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('operator_name', models.CharField(max_length=255, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='pnm.asset')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pnm.manager')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_receiver', to='pnm.manager')),
            ],
        ),
    ]
