# Generated by Django 5.1.7 on 2025-06-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pnm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='chargers',
            new_name='charges',
        ),
    ]
