# Generated by Django 5.1.7 on 2025-06-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnm', '0002_rename_chargers_asset_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='emi_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='emi_payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='emi_start_date',
            field=models.DateField(null=True),
        ),
    ]
