# Generated by Django 5.2.3 on 2025-06-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnm', '0003_alter_asset_emi_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
