# Generated by Django 5.2.3 on 2025-06-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnm', '0004_operator_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrent',
            name='charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
