# Generated by Django 5.2.3 on 2025-06-19 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnm', '0005_monthlyrent_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetails',
            name='operator_name',
        ),
        migrations.AddField(
            model_name='tripdetails',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pnm.operator'),
        ),
    ]
