# Generated by Django 5.2.3 on 2025-06-25 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnm', '0007_asset_fitness_amount_asset_permit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dieselentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
