# Generated by Django 5.2.3 on 2025-06-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnm', '0008_alter_breakdown_date_alter_breakdown_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dieselentry',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
